<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import AppShell from '@/components/AppShell.vue'
import { catalogApi, type CampaignInput, type ChannelInput, type CreativeInput } from '@/api/catalog'
import { useAuthStore } from '@/stores/auth'
import type { Campaign, Channel, Creative, Game } from '@/types/catalog'

const auth = useAuthStore(); const activeTab = ref('campaigns'); const loading = ref(false); const saving = ref(false); const error = ref('')
const games = ref<Game[]>([]); const channels = ref<Channel[]>([]); const campaigns = ref<Campaign[]>([]); const creatives = ref<Creative[]>([])
const dialog = ref<'channel'|'campaign'|'creative'|''>(''); const editingID = ref('')
const dialogVisible = computed({ get: () => Boolean(dialog.value), set: (visible: boolean) => { if (!visible) dialog.value = '' } })
const channelForm = reactive<ChannelInput>({ code: '', name: '', provider: 'MOCK', status: 'ACTIVE' })
const campaignForm = reactive<CampaignInput>({ game_id: '', channel_id: '', external_id: '', name: '', country: 'US', daily_budget: '0', currency: 'USD', status: 'ACTIVE' })
const creativeForm = reactive<CreativeInput>({ campaign_id: '', external_id: '', name: '', type: 'VIDEO', status: 'ACTIVE' })
const canChannel = () => auth.hasAnyRole(['ADMIN']); const canCampaign = () => auth.hasAnyRole(['ADMIN','MANAGER']); const canCreative = () => auth.hasAnyRole(['ADMIN','MANAGER','OPERATOR'])
function messageOf(value: any) { return value.response?.data?.message || '请求失败，请稍后重试。' }
function gameName(id: string) { return games.value.find(x => x.id === id)?.name || id }
function channelName(id: string) { return channels.value.find(x => x.id === id)?.name || id }
function campaignName(id: string) { return campaigns.value.find(x => x.id === id)?.name || id }
async function load() { loading.value = true; error.value = ''; try { [games.value, channels.value, campaigns.value, creatives.value] = await Promise.all([catalogApi.listGames(), catalogApi.listChannels(), catalogApi.listCampaigns(), catalogApi.listCreatives()]) } catch (e) { error.value = messageOf(e) } finally { loading.value = false } }
function openChannel(row?: Channel) { editingID.value=row?.id||''; Object.assign(channelForm, row ? {code:row.code,name:row.name,provider:row.provider,status:row.status}:{code:'',name:'',provider:'MOCK',status:'ACTIVE'}); dialog.value='channel' }
function openCampaign(row?: Campaign) { editingID.value=row?.id||''; Object.assign(campaignForm, row ? {game_id:row.game_id,channel_id:row.channel_id,external_id:row.external_id,name:row.name,country:row.country,daily_budget:String(row.daily_budget),currency:row.currency,status:row.status}:{game_id:games.value[0]?.id||'',channel_id:channels.value[0]?.id||'',external_id:'',name:'',country:'US',daily_budget:'0',currency:'USD',status:'ACTIVE'}); dialog.value='campaign' }
function openCreative(row?: Creative) { editingID.value=row?.id||''; Object.assign(creativeForm, row ? {campaign_id:row.campaign_id,external_id:row.external_id,name:row.name,type:row.type,status:row.status}:{campaign_id:campaigns.value[0]?.id||'',external_id:'',name:'',type:'VIDEO',status:'ACTIVE'}); dialog.value='creative' }
async function save() { saving.value=true; error.value=''; try { if(dialog.value==='channel'){ if(editingID.value) await catalogApi.updateChannel(editingID.value,channelForm); else await catalogApi.createChannel(channelForm) } if(dialog.value==='campaign'){ if(editingID.value) await catalogApi.updateCampaign(editingID.value,campaignForm); else await catalogApi.createCampaign(campaignForm) } if(dialog.value==='creative'){ if(editingID.value) await catalogApi.updateCreative(editingID.value,creativeForm); else await catalogApi.createCreative(creativeForm) } dialog.value=''; await load() } catch(e){ error.value=messageOf(e) } finally { saving.value=false } }
onMounted(load)
</script>

<template><AppShell>
  <div class="page-heading"><div><span class="eyebrow">DELIVERY ASSETS</span><h2>投放资产</h2><p>统一维护渠道、广告计划与素材引用。</p></div></div>
  <el-alert v-if="error" :title="error" type="error" show-icon closable @close="error=''" />
  <div v-if="loading" class="loading-panel">正在加载投放资产…</div>
  <el-tabs v-else v-model="activeTab" class="asset-tabs">
    <el-tab-pane label="广告计划" name="campaigns"><div class="table-toolbar"><span>{{ campaigns.length }} 个计划</span><el-button v-if="canCampaign()" type="primary" @click="openCampaign()">新增计划</el-button></div><el-empty v-if="!campaigns.length" description="暂无广告计划" /><el-table v-else :data="campaigns"><el-table-column prop="external_id" label="外部 ID" /><el-table-column prop="name" label="计划名称" /><el-table-column label="游戏"><template #default="s">{{gameName(s.row.game_id)}}</template></el-table-column><el-table-column label="渠道"><template #default="s">{{channelName(s.row.channel_id)}}</template></el-table-column><el-table-column prop="country" label="国家" width="80" /><el-table-column label="日预算"><template #default="s">{{s.row.currency}} {{s.row.daily_budget}}</template></el-table-column><el-table-column v-if="canCampaign()" label="操作" width="80"><template #default="s"><el-button link @click="openCampaign(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="渠道" name="channels"><div class="table-toolbar"><span>{{channels.length}} 个渠道</span><el-button v-if="canChannel()" type="primary" @click="openChannel()">新增渠道</el-button></div><el-empty v-if="!channels.length" description="暂无渠道" /><el-table v-else :data="channels"><el-table-column prop="code" label="代码" /><el-table-column prop="name" label="名称" /><el-table-column prop="provider" label="Provider" /><el-table-column prop="status" label="状态" /><el-table-column v-if="canChannel()" label="操作" width="80"><template #default="s"><el-button link @click="openChannel(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="素材" name="creatives"><div class="table-toolbar"><span>{{creatives.length}} 个素材</span><el-button v-if="canCreative()" type="primary" @click="openCreative()">新增素材</el-button></div><el-empty v-if="!creatives.length" description="暂无素材" /><el-table v-else :data="creatives"><el-table-column prop="external_id" label="外部 ID" /><el-table-column prop="name" label="素材名称" /><el-table-column label="所属计划"><template #default="s">{{campaignName(s.row.campaign_id)}}</template></el-table-column><el-table-column prop="type" label="类型" /><el-table-column prop="status" label="状态" /><el-table-column v-if="canCreative()" label="操作" width="80"><template #default="s"><el-button link @click="openCreative(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
  </el-tabs>

	<el-dialog v-model="dialogVisible" :title="editingID?'编辑投放资产':'新增投放资产'" width="560px">
    <el-form v-if="dialog==='channel'" label-position="top"><el-form-item label="渠道代码"><el-input v-model="channelForm.code" /></el-form-item><el-form-item label="名称"><el-input v-model="channelForm.name" /></el-form-item><el-form-item label="Provider"><el-input v-model="channelForm.provider" /></el-form-item><el-form-item label="状态"><el-select v-model="channelForm.status"><el-option label="ACTIVE" value="ACTIVE"/><el-option label="INACTIVE" value="INACTIVE"/></el-select></el-form-item></el-form>
    <el-form v-if="dialog==='campaign'" label-position="top"><div class="form-grid"><el-form-item label="游戏"><el-select v-model="campaignForm.game_id"><el-option v-for="g in games" :key="g.id" :label="g.name" :value="g.id"/></el-select></el-form-item><el-form-item label="渠道"><el-select v-model="campaignForm.channel_id"><el-option v-for="c in channels" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item></div><el-form-item label="外部 ID"><el-input v-model="campaignForm.external_id"/></el-form-item><el-form-item label="名称"><el-input v-model="campaignForm.name"/></el-form-item><div class="form-grid"><el-form-item label="国家"><el-input v-model="campaignForm.country" maxlength="2"/></el-form-item><el-form-item label="日预算"><el-input v-model="campaignForm.daily_budget"/></el-form-item></div><el-form-item label="状态"><el-select v-model="campaignForm.status"><el-option label="ACTIVE" value="ACTIVE"/><el-option label="PAUSED" value="PAUSED"/><el-option label="ARCHIVED" value="ARCHIVED"/></el-select></el-form-item></el-form>
    <el-form v-if="dialog==='creative'" label-position="top"><el-form-item label="广告计划"><el-select v-model="creativeForm.campaign_id"><el-option v-for="c in campaigns" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="外部 ID"><el-input v-model="creativeForm.external_id"/></el-form-item><el-form-item label="名称"><el-input v-model="creativeForm.name"/></el-form-item><div class="form-grid"><el-form-item label="类型"><el-select v-model="creativeForm.type"><el-option label="VIDEO" value="VIDEO"/><el-option label="IMAGE" value="IMAGE"/><el-option label="PLAYABLE" value="PLAYABLE"/><el-option label="TEXT" value="TEXT"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="creativeForm.status"><el-option label="ACTIVE" value="ACTIVE"/><el-option label="INACTIVE" value="INACTIVE"/><el-option label="ARCHIVED" value="ARCHIVED"/></el-select></el-form-item></div></el-form>
    <template #footer><el-button @click="dialog=''">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template>
  </el-dialog>
</AppShell></template>
