CREATE TABLE research_schedules (
  id CHAR(36) PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  game_id CHAR(36) NULL,
  campaign_id CHAR(36) NULL,
  category VARCHAR(30) NOT NULL,
  query VARCHAR(400) NOT NULL,
  query_hash CHAR(64) NOT NULL,
  idempotency_key CHAR(64) NOT NULL,
  country VARCHAR(2) NULL,
  search_lang VARCHAR(12) NULL,
  freshness VARCHAR(2) NULL,
  result_count INT NOT NULL,
  interval_minutes INT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  next_run_at DATETIME(3) NULL,
  last_run_at DATETIME(3) NULL,
  last_status VARCHAR(20) NULL,
  last_error_code VARCHAR(50) NULL,
  last_error_message TEXT NULL,
  lock_token CHAR(36) NULL,
  locked_until DATETIME(3) NULL,
  created_by CHAR(36) NOT NULL,
  updated_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uidx_research_schedule_key (tenant_id, idempotency_key),
  KEY idx_research_schedules_tenant (tenant_id, enabled, created_at),
  KEY idx_research_schedules_due (enabled, next_run_at, locked_until),
  KEY idx_research_schedules_game (game_id),
  KEY idx_research_schedules_campaign (campaign_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE research_schedule_runs (
  id CHAR(36) PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  schedule_id CHAR(36) NOT NULL,
  scheduled_for DATETIME(3) NOT NULL,
  status VARCHAR(20) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  query_hash CHAR(64) NOT NULL,
  result_count INT NOT NULL DEFAULT 0,
  imported_count INT NOT NULL DEFAULT 0,
  duplicate_count INT NOT NULL DEFAULT 0,
  skipped_count INT NOT NULL DEFAULT 0,
  error_code VARCHAR(50) NULL,
  error_message TEXT NULL,
  requested_by CHAR(36) NOT NULL,
  claim_token CHAR(36) NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uidx_research_schedule_run (tenant_id, schedule_id, scheduled_for),
  KEY idx_research_schedule_runs_tenant (tenant_id, status, scheduled_for),
  KEY idx_research_schedule_runs_schedule (schedule_id, scheduled_for)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE research_sources
  ADD COLUMN discovery_schedule_id CHAR(36) NULL AFTER discovery_query_hash,
  ADD KEY idx_research_source_schedule (discovery_schedule_id, created_at);
